name: dataexplore 
version: '0.7.3' 
summary: data analysis package
description: |
  DataExplore is an open source desktop application for data analysis and plotting
  intended for use in both research and education. It is intended primarily for
   non-programmers who need to do relatively advanced table manipulation methods.

grade: stable 
confinement: strict 

apps:
  dataexplore:
    command: bin/dataexplore
parts:
  dataexplore:    
    plugin: python
    python-version: python3
    source: ../
    stage-packages: 
     - python3-dev
     - python3-tk
